##### 1. Load a CSV dataset into a Pandas DataFrame.

In [53]:
import pandas as pd
df=pd.read_csv(r"C:\Users\aditi\OneDrive\Desktop\Celebal_Internship\Week1\Combined_dataset.csv")

##### 2. Explore data (head/tail, shape, columns, data types).

In [54]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [55]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [56]:
print("Number of rows and columns:" , df.shape)

Number of rows and columns: (1000, 24)

In [57]:
print("Columns are:", df.columns)

Columns are: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [58]:
print("columns -> types: ")
print(df.dtypes)

columns -> types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

##### 3. Handle missing values (identify, fill/drop).

In [59]:
print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [60]:
# Fill text/object columns

df['discount'] = df['discount'].fillna(0)

df['what_customers_said'] = df['what_customers_said'].fillna('No customer reviews')

df['seller_name'] = df['seller_name'].fillna('Unknown Seller')

df['videos'] = df['videos'].fillna('No Videos')

df['seller_information'] = df['seller_information'].fillna('Seller information not available')

df['variations'] = df['variations'].fillna('No Variations')

##### 4. Perform basic operations (filter rows, select columns).

In [61]:
#practicing filtering of rows
df_cheap_products = df[df['initial_price'] < 1000]
print(df_cheap_products)

     product_id                    title  \
20     22120138          Ed-a-Mamma Baby
23     17372928         The Souled Store
24     15115018                   Jockey
25     22063882  GROVERSONS Paris Beauty
26     19219450                    Susie
..          ...                      ...
966    12953958              Allen Solly
967    22629260                      max
970    19264534           Flying Machine
987     7349545            Fantasy World
999    18601682                  BOLDFIT

                                   product_description  rating  ratings_count  \
20   Infant Boys Pack Of 2 Printed Pure Cotton Body...     4.2              5
23            Men Blue & White Abstract Printed Boxers     4.5             22
24   Non-Wired Non-Padded Combed Cotton Workout Bra...     4.4           1582
25    Non Padded Cotton Seamless Non-Wired T-shirt Bra     4.0             25
26         Black Solid Cotton T-Shirt Bra - Anti-Odour     4.3             12
..                                                 ...     ...            ...
966   Men Maroon Solid Polo Collar Pure Cotton T-shirt     4.4            409
967          Striped Polo Collar Short Sleeves T-shirt     4.4              7
970  Men Black & White Printed Pure Cotton Slim Fit...     4.0            102
987                          Unisex Grey Digital Watch     3.7            119
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount final_price currency  \
20             999      30.0   "₹699.00"      INR
23             799      54.0   "₹367.00"      INR
24             579       0.0   "₹579.00"      INR
25             399      25.0   "₹299.00"      INR
26             749      50.0   "₹374.00"      INR
..             ...       ...         ...      ...
966            999      40.0   "₹599.00"      INR
967            799      40.0   "₹479.00"      INR
970            999      61.0   "₹389.00"      INR
987            499      20.0   "₹499.00"      INR
999            699      31.0   "₹699.00"      INR

                                                images  ...  \
20   http://assets.myntassets.com/assets/images/221...  ...
23   http://assets.myntassets.com/assets/images/173...  ...
24   http://assets.myntassets.com/assets/images/151...  ...
25   http://assets.myntassets.com/assets/images/220...  ...
26   http://assets.myntassets.com/assets/images/192...  ...
..                                                 ...  ...
966  http://assets.myntassets.com/assets/images/129...  ...
967  http://assets.myntassets.com/assets/images/226...  ...
970  http://assets.myntassets.com/assets/images/192...  ...
987  http://assets.myntassets.com/assets/images/734...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars  \
20   {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...
23   {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...
24   {"1_star":90,"2_stars":25,"3_stars":93,"4_star...
25   {"1_star":3,"2_stars":0,"3_stars":3,"4_stars":...
26   {"1_star":0,"2_stars":2,"3_stars":1,"4_stars":...
..                                                 ...
966  {"1_star":17,"2_stars":6,"3_stars":26,"4_stars...
967  {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...
970  {"1_star":8,"2_stars":4,"3_stars":15,"4_stars"...
987  {"1_star":20,"2_stars":8,"3_stars":13,"4_stars...
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...

                                   what_customers_said  \
20                                 No customer reviews
23   [{"percentage":"100","value_name":"Fit, Just R...
24                                 No customer reviews
25                                 No customer reviews
26                                 No customer reviews
..                                                 ...
966  [{"percentage":"96","value_name":"Fit, Just Ri...
967                                No customer reviews
970  [{"percentage":"67","value_name":"Fit, Just Ri...
987                                No customer reviews
999                                No customer reviews

                                           seller_name  \
20   ETE███LIA███EAT█████████CHA███████████████████...
23                          THE███ULE███TOR█████████D.
24                                      Tru███m R███il
25                      Gro███son███ppa█████████Ltd███
26                   GEN███AD ███AIL█████████LIM██████
..                                                 ...
966                  Wes███ry ███din█████████d_M██████
967                     Lan███rk ███ine█████████t L███
970                  ARV███ LI███TYL█████████LIM██████
987                                     Unknown Seller
999                                     Unknown Seller

                                                 sizes  \
20   [{"size":"0-3M","value":"18.9in","value_name":...
23   [{"size":"S","value":"30.0in","value_name":"To...
24   [{"size":"S","value":"34.0in","value_name":"Ov...
25   [{"size":"30B","value":"31.0in","value_name":"...
26   [{"size":"30B","value":"31.0in to 32.0in","val...
..                                                 ...
966  [{"size":"S","value":"39.0in","value_name":"Ch...
967  [{"size":"S","value":"36.0in","value_name":"Ch...
970  [{"size":"XS","value":"34.0in","value_name":"C...
987                               [{"size":"Onesize"}]
999                                [{"size":"Medium"}]

                                                videos  \
20                                           No Videos
23                                           No Videos
24                                           No Videos
25                                           No Videos
26                                           No Videos
..                                                 ...
966  ["rw-12953958_cae700","https://videos.myntasse...
967                                          No Videos
970                                          No Videos
987                              ["rw-7349545_cae700"]
999                                          No Videos

                                    seller_information  \
20   1A ███I H███E S█████████CH ███████████████████...
23   F6 ███02,███umi█████████dus███████████████████...
24   Sho███o. ███-10█████████enu███████████████████...
25   sec███ A-███Plo█████████, I███████████████████...
26   2ND███OOR███O 1█████████MAL███████████████████...
..                                                 ...
966  Gro███ Fl███, N█████████old███████████████████...
967  #41███42/███bla█████████ pa███████████████████...
970  10T███LOO███DU █████████ITY███████████████████...
987                   Seller information not available
999                   Seller information not available

                             variations  \
20                        No Variations
23                        No Variations
24   [{},{},{},{},{},{},{},{},{},{},{}]
25                        No Variations
26                                 [{}]
..                                  ...
966                       No Variations
967                          [{},{},{}]
970                                [{}]
987                       No Variations
999                       [{},{},{},{}]

                                            best_offer  \
20   {"applicable_on":"Orders above Rs. 999 (only o...
23   {"applicable_on":"Orders above Rs. 649 (only o...
24   {"applicable_on":"Orders above Rs. 649 (only o...
25   {"applicable_on":"Orders above Rs. 649 (only o...
26   {"applicable_on":"Orders above Rs. 649 (only o...
..                                                 ...
966  {"applicable_on":"Orders above Rs. 649 (only o...
967  {"applicable_on":"Orders above Rs. 649 (only o...
970  {"applicable_on":"Orders above Rs. 649 (only o...
987                                                 {}
999                                                 {}

                                           more_offers   category
20   [{"offer_name":"10% Instant Discount on IndusI...   bodysuit
23   [{"offer_name":"10% Instant Discount on IndusI...     boxers
24   [{"offer_name":"10% Instant Discount on IndusI...        bra
25   [{"offer_name":"10% Instant Discount on IndusI...        bra
26   [{"offer_name":"10% Instant Discount on IndusI...        bra
..                                                 ...        ...
966  [{"offer_name":"10% Instant Discount on IndusI...    tshirts
967  [{"offer_name":"10% Instant Discount on IndusI...    tshirts
970  [{"offer_name":"10% Instant Discount on IndusI...    tshirts
987  [{"offer_name":"10% Instant Discount on Citi C...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[166 rows x 24 columns]

In [62]:
df_filtered=df[['product_id', 'title','initial_price', 'discount']]
# Calculating price after discount,[assuming discount is in absolute terms and not percentage]
df_filtered['price'] = df_filtered['initial_price'] - df_filtered['discount']
df_filtered.head()

   product_id           title  initial_price  discount   price
0     8376765     Lino Perros           3995      58.0  3937.0
1     9136281  Tommy Hilfiger           2899      35.0  2864.0
2    17633752           Lavie           2999      65.0  2934.0
3     1376949          F Gear           1675      52.0  1623.0
4    13939916       MYTRIDENT           2899      17.0  2882.0

In [63]:
#since quantity column is missing, i am creating a new column quantity and filling it with random values between 1 and 10 for each row
import numpy as np
df_filtered['quantity'] = np.random.randint(1, 11, size=len(df_filtered))
df_filtered.head()

   product_id           title  initial_price  discount   price  quantity
0     8376765     Lino Perros           3995      58.0  3937.0         2
1     9136281  Tommy Hilfiger           2899      35.0  2864.0         2
2    17633752           Lavie           2999      65.0  2934.0         6
3     1376949          F Gear           1675      52.0  1623.0         7
4    13939916       MYTRIDENT           2899      17.0  2882.0         3

##### 5. Remove duplicates.

In [64]:
df_filtered.drop_duplicates(subset='product_id', inplace=True)
print(len(df_filtered))

1000

##### 6. Create a derived column (total_amount = price * quantity).

In [65]:
df_filtered['total_amount'] = df_filtered['price'] * df_filtered['quantity']
df_filtered.head()

,product_id,title,initial_price,discount,price,quantity,total_amount
0,8376765,Lino Perros,3995,58.0,3937.0,2,7874.0
1,9136281,Tommy Hilfiger,2899,35.0,2864.0,2,5728.0
2,17633752,Lavie,2999,65.0,2934.0,6,17604.0
3,1376949,F Gear,1675,52.0,1623.0,7,11361.0
4,13939916,MYTRIDENT,2899,17.0,2882.0,3,8646.0

In [67]:
total_amount_sum = df_filtered['total_amount'].sum()
print("Total amount sum:", total_amount_sum)

Total amount sum: 14373852.0

##### 7. Save the cleaned dataset as a new CSV file.

In [66]:
df_filtered.to_csv(r"C:\Users\aditi\OneDrive\Desktop\Celebal_Internship\Week1\Processed_dataset.csv", index=False)